#!/usr/bin/env python3
"""
scripts/figures/boundary_limited_error.py

N2 -- the keystone of the label-ceiling narrative: at the pretrained baseline the
residual segmentation error is dominated by BOUNDARY-localised label ambiguity,
not interior (capacity) failure. Three panels, one cell (baseline):

  (a) Trimap IoU recovery.  Per-class IoU re-scored while excluding a widening band
      around GROUND-TRUTH class boundaries. IoU climbs steeply then plateaus -> the
      error lives in the boundary shell. Per-seed mean over 10 seeds (+/-1 SD band),
      NOT the ensemble argmax (PLOT_PLAN FLAG-1). Single-label analogue of Ortiz et
      al. (2025) BS_gamma_beta recovery.

  (b) Error vs distance-to-boundary.  Foreground misclassification rate vs distance to
      the nearest GT boundary (log m). Decays to an interior floor -- error is
      concentrated at boundaries. Non-circular (stratified by GT boundaries, never by
      predictions). The matching entropy-vs-distance decay now lives in the uncertainty
      figure (Fig 13b), decomposed into aleatoric and epistemic parts.

  (c) Boundary-band vs interior error, per class.  Paired bars: foreground error rate in
      the boundary band (<=1.5 m of a GT boundary) vs the interior floor (>8 m). Forest and
      Settlement collapse to ~0 in the interior (purely boundary-limited -> label ceiling);
      Seminatural keeps a non-zero interior floor (genuine interior/semantic error), which we
      own. Discriminates failure modes per class, unlike a Mask/Boundary-IoU gap (which just
      tracks Mask-IoU level). Cheng et al. (2021) Boundary-IoU + d-sweep are still computed in
      the JSON (boundary_iou block) for a supplementary table.

Data (all three panels from ONE file, all on the same 219 Irish val tiles):
  analysis/label_ceiling/boundary_trimap_<cell>.json
    recovery_trimap   -> (a)   boundary_iou -> (c)
    error_vs_distance -> (b)   error_rate_foreground + entropy_total_foreground
  regenerated by: PYTHONPATH=. python scripts/analysis/boundary_trimap_iou.py

Output:
  figures/boundary_limited_error.pdf  (+ .png for QC)

  New-narrative figure; intentionally NOT in build_all_figures.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

# Palette shared with frequency_vs_difficulty.py / class_distributions.py.
# Keys are STUDENT_CLASSES names (geoseg.taxonomy), matching the analysis JSON.
RGB = {
    "Forest": (250, 62, 119),
    "Grassland": (168, 232, 84),
    "Cropland": (242, 180, 92),
    "Settlement": (59, 141, 247),
    "Seminatural": (255, 214, 33),
}
SHORT = {
    "Forest": "Forest",
    "Grassland": "Grassland",
    "Cropland": "Cropland",
    "Settlement": "Settlement",
    "Seminatural": "Semi-nat.",
}
# Class order for the panel-(c) bars (canonical foreground order).
BAR_ORDER = ["Forest", "Grassland", "Cropland", "Settlement", "Seminatural"]
# Narrative classes traced in panel (a).
TRACE = ["Forest", "Settlement", "Seminatural"]
GSD_M = 0.5


def find_repo_root() -> Path:
    p = Path.cwd().resolve()
    for _ in range(10):
        if (p / "data").is_dir() and (p / "scripts").is_dir():
            return p
        if p == p.parent:
            break
        p = p.parent
    p = Path(__file__).resolve()
    for parent in p.parents:
        if (parent / "data").is_dir() and (parent / "scripts").is_dir():
            return parent
    raise RuntimeError("Could not find repo root")


def setup_font(use_tex: bool):
    rc = {
        "font.family": "serif",
        "font.serif": ["Computer Modern Roman"],
        "axes.labelsize": 13,
        "font.size": 12,
        "axes.titlesize": 14,
        "legend.fontsize": 12,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "axes.axisbelow": True,
        "figure.dpi": 150,
    }
    if use_tex:
        rc["text.usetex"] = True
        rc["text.latex.preamble"] = r"\usepackage{amsmath}"
    else:
        rc["text.usetex"] = False
        rc["mathtext.fontset"] = "cm"
    plt.rcParams.update(rc)


def col(name):
    return np.array(RGB[name]) / 255.0


def panel_recovery(ax, rec, use_tex):
    """(a) per-class per-seed-mean trimap recovery."""
    radii_px = rec["radii_px"]
    # excluded-band width (m): baseline N=-1 -> 0; otherwise ~(N+1) px excised.
    xb = [0.0 if N < 0 else (N + 1) * GSD_M for N in radii_px]
    for name in TRACE:
        y = np.array(rec["per_seed_class_iou_mean"][name])
        sd = np.array(rec["per_seed_class_iou_std"][name])
        ax.plot(xb, y, "-o", ms=3.5, lw=1.4, color=col(name), label=SHORT[name], zorder=3)
        ax.fill_between(xb, y - sd, y + sd, color=col(name), alpha=0.15, lw=0, zorder=1)
    ymac = np.array(rec["per_seed_macro_mean"])
    ax.plot(xb, ymac, "--", lw=1.3, color="#444444", label="macro (fg)", zorder=2)
    ax.set_xlabel("excluded boundary band (m)" if not use_tex
                  else r"excluded boundary band (m)")
    ax.set_ylabel("per-class IoU")
    ax.set_title("(a)")
    ax.grid(True, ls=":", lw=0.5, color="#cccccc")


def panel_distance(ax, err, use_tex):
    """(b) foreground error rate vs distance-to-boundary (single axis).
    Entropy-vs-distance now lives in the uncertainty figure (Fig 13b)."""
    em = err["edges_m"]
    # bin centres; final open bin (inf) plotted at 1.4x the last finite edge.
    fin = [e for e in em if np.isfinite(e)]
    cen = [(a + b) / 2 for a, b in zip(fin[:-1], fin[1:])] + [fin[-1] * 1.4]
    rate = np.array(err["error_rate_foreground"])
    ax.plot(cen, rate, "-o", ms=3.5, lw=1.5, color="#b2182b", zorder=3)
    ax.set_xscale("log")
    ax.set_xlabel("distance to GT boundary (m, log)")
    ax.set_ylabel("misclassification rate")
    ax.set_title("(b)")
    ax.grid(True, ls=":", lw=0.5, color="#cccccc")


def panel_interior_floor(ax, bvi, use_tex):
    """(c) per-class error rate in the boundary band vs the interior floor.

    Boundary-limited (label-ceiling) classes collapse to ~0 in the interior; a class with
    a non-zero interior floor (Seminatural) has genuine interior/semantic error."""
    pc = bvi["per_class"]
    bmax, imin = bvi["boundary_max_m"], bvi["interior_min_m"]
    names = BAR_ORDER
    x = np.arange(len(names))
    w = 0.38
    bnd = [pc[n]["boundary_error"] for n in names]
    inr = [pc[n]["interior_error"] for n in names]
    cols = [col(n) for n in names]
    ax.bar(x - w / 2, bnd, w, color=cols, edgecolor="black", lw=0.6)
    ax.bar(x + w / 2, inr, w, color=cols, edgecolor="black", lw=0.6, alpha=0.4, hatch="///")
    for xi, v in zip(x, inr):
        ax.annotate(f"{v:.2f}", (xi + w / 2, v + 0.015), ha="center", fontsize=11, color="#333333")
    ax.set_xticks(x)
    ax.set_xticklabels([SHORT[n] for n in names], rotation=30, ha="right")
    ax.set_ylabel("misclassification rate")
    ax.set_ylim(0, max(bnd) * 1.18)
    ax.set_title("(c)")
    ax.grid(True, axis="y", ls=":", lw=0.5, color="#cccccc")
    from matplotlib.patches import Patch
    blab = (rf"boundary ($\leq{bmax:g}$\,m)" if use_tex else f"boundary (<={bmax:g} m)")
    ilab = (rf"interior ($>{imin:g}$\,m)" if use_tex else f"interior (>{imin:g} m)")
    handles = [Patch(facecolor="#999999", edgecolor="black", label=blab),
               Patch(facecolor="#999999", edgecolor="black", alpha=0.4, hatch="///", label=ilab)]
    ax.legend(handles=handles, loc="upper right", frameon=False)


def render(root, out_dir, cell, use_tex):
    setup_font(use_tex)
    bt = json.load(open(root / f"analysis/label_ceiling/boundary_trimap_{cell}.json"))

    fig, axes = plt.subplots(1, 3, figsize=(9.8, 4.5))
    panel_recovery(axes[0], bt["recovery_trimap"], use_tex)
    panel_distance(axes[1], bt["error_vs_distance"], use_tex)
    panel_interior_floor(axes[2], bt["error_vs_distance"]["boundary_vs_interior"], use_tex)

    # Shared class legend at the bottom (panels a and c use the class colours).
    from matplotlib.lines import Line2D
    handles = [Line2D([0], [0], color=col(n), lw=2.4, label=SHORT[n]) for n in BAR_ORDER]
    handles.append(Line2D([0], [0], color="#444444", lw=1.6, ls="--", label="macro (fg)"))
    fig.legend(handles=handles, loc="lower center", ncol=6, frameon=False,
               bbox_to_anchor=(0.5, -0.01), columnspacing=1.4, handletextpad=0.5)
    fig.tight_layout(rect=[0, 0.07, 1, 1])

    out_dir.mkdir(parents=True, exist_ok=True)
    pdf = out_dir / "boundary_limited_error.pdf"
    png = out_dir / "boundary_limited_error.png"
    fig.savefig(pdf, bbox_inches="tight")
    fig.savefig(png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[boundary_limited_error] cell={cell} -> {pdf}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", default="stage1_baseline")
    ap.add_argument("--out-dir", default="figures")
    ap.add_argument("--no-tex", action="store_true")
    args = ap.parse_args()
    root = find_repo_root()
    out_dir = (root / args.out_dir).resolve()
    use_tex = not args.no_tex
    try:
        render(root, out_dir, args.cell, use_tex)
    except Exception as e:
        if not use_tex:
            raise
        print(f"[boundary_limited_error] usetex failed ({e}); retrying with mathtext")
        render(root, out_dir, args.cell, use_tex=False)


if __name__ == "__main__":
    main()
