#!/usr/bin/env python3
"""
scripts/figures/build_all_figures.py

Single entry point to reproduce the manuscript figures that render directly to figures/.

Usage:
  python scripts/figures/build_all_figures.py [--device cuda|cpu] [--skip <name> ...]

Figures use stable DESCRIPTIVE names (the printed numbers are assigned by LaTeX).
  - workflow_pipeline, mitigation_axes, oem_mapping are TikZ (.tex), compiled with
    pdflatex and copied to figures/.
  - study_area, class_distributions, ablation_qualitative, confusion_matrices,
    factorial_effects, frequency_vs_difficulty, reliability_ece, uncertainty_quality,
    boundary_limited_error are Python scripts that write directly to figures/.
  - ablation_qualitative takes --device (model inference); the rest read saved
    outputs. Pass --skip <name> to skip by the descriptive key.

Not built here: the uncertainty-overlay and class-pair-boundary figures are produced
by scripts/analysis/*, and the graphical abstract by graphical_abstract_panels.py +
graphical_abstract_tikz.tex.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPTS_DIR.parent.parent
FIGURES_DIR = REPO_ROOT / "figures"


def run_py(script: Path, extra_args: list[str], device: str) -> bool:
    if not script.exists():
        print(f"\nERROR: script not found: {script}")
        return False
    cmd = [sys.executable, str(script), f"--device={device}", *extra_args]
    print(f"\n{'='*60}\nRunning: {script.name}\n{'='*60}")
    return subprocess.run(cmd, cwd=str(REPO_ROOT)).returncode == 0


def run_py_no_device(script: Path) -> bool:
    """For scripts that do not accept a --device argument."""
    if not script.exists():
        print(f"\nERROR: script not found: {script}")
        return False
    cmd = [sys.executable, str(script)]
    print(f"\n{'='*60}\nRunning: {script.name}\n{'='*60}")
    return subprocess.run(cmd, cwd=str(REPO_ROOT)).returncode == 0


def run_tex(tex: Path) -> bool:
    """Compile a standalone TikZ figure and copy the PDF into figures/."""
    if not tex.exists():
        print(f"\nERROR: source not found: {tex}")
        return False
    print(f"\n{'='*60}\nCompiling: {tex.name}\n{'='*60}")
    cmd = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex.name]
    ok = subprocess.run(cmd, cwd=str(SCRIPTS_DIR)).returncode == 0
    produced = SCRIPTS_DIR / (tex.stem + ".pdf")
    if not ok or not produced.exists():
        return False
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(produced, FIGURES_DIR / produced.name)
    # tidy LaTeX side products
    for ext in (".aux", ".log"):
        (SCRIPTS_DIR / (tex.stem + ext)).unlink(missing_ok=True)
    return True


def main() -> None:
    ap = argparse.ArgumentParser(description="Build all manuscript figures.")
    ap.add_argument("--device", default="cuda", choices=["cuda", "cpu"],
                    help="Device for scripts that run model inference (default: cuda).")
    ap.add_argument("--skip", nargs="*", default=[],
                    help="Descriptive figure keys to skip, e.g. --skip study_area confusion_matrices")
    args = ap.parse_args()

    skip = set(args.skip)

    # Manuscript figures that write directly to figures/ (descriptive names; LaTeX
    # assigns the printed numbers). oem_mapping's numeric content is generated by
    # _gen_mapping_values.py from the frozen teacher confusion.
    figures: list[tuple[str, callable]] = [
        ("workflow_pipeline",      lambda: run_tex(SCRIPTS_DIR / "workflow_pipeline.tex")),
        ("mitigation_axes",        lambda: run_tex(SCRIPTS_DIR / "mitigation_axes.tex")),
        ("oem_mapping",            lambda: run_tex(SCRIPTS_DIR / "oem_mapping.tex")),
        ("study_area",             lambda: run_py_no_device(SCRIPTS_DIR / "study_area.py")),
        ("class_distributions",    lambda: run_py_no_device(SCRIPTS_DIR / "class_distributions.py")),
        ("ablation_qualitative",   lambda: run_py(SCRIPTS_DIR / "ablation_qualitative.py", [], args.device)),
        ("confusion_matrices",     lambda: run_py_no_device(SCRIPTS_DIR / "confusion_matrices.py")),
        ("factorial_effects",      lambda: run_py_no_device(SCRIPTS_DIR / "factorial_effects.py")),
        ("frequency_vs_difficulty",lambda: run_py_no_device(SCRIPTS_DIR / "frequency_vs_difficulty.py")),
        ("reliability_ece",        lambda: run_py_no_device(SCRIPTS_DIR / "reliability_ece.py")),
        ("uncertainty_quality",    lambda: run_py_no_device(SCRIPTS_DIR / "uncertainty_quality.py")),
        ("boundary_limited_error", lambda: run_py_no_device(SCRIPTS_DIR / "boundary_limited_error.py")),
    ]

    results: dict[str, bool | str] = {}
    for fig_num, runner in figures:
        if fig_num in skip:
            results[fig_num] = "skipped"
            print(f"\nSkipping Figure {fig_num} (--skip).")
            continue
        results[fig_num] = runner()

    print(f"\n{'='*60}\nBuild summary\n{'='*60}")
    for fig_num, status in results.items():
        marker = "SKIP" if status == "skipped" else ("OK  " if status is True else "FAIL")
        print(f"  Figure {fig_num}: {marker}")

    failed = [n for n, s in results.items() if s is False]
    if failed:
        print(f"\n{len(failed)} figure(s) failed: {', '.join(failed)}")
        sys.exit(1)
    print("\nAll requested figures built successfully.")


if __name__ == "__main__":
    main()
